package com.lijs.seckill.util;

/**
 * Parses the restricted expression generated by
 * {@link com.lijs.seckill.service.VerifyCodeService} without a runtime script engine.
 */
public class ArithmeticExpression {

    private final String expression;
    private int position;

    public ArithmeticExpression(String expression) {
        this.expression = expression;
    }

    public int parse() {
        if (expression == null || expression.isEmpty()) {
            throw new IllegalArgumentException("Verification expression is empty");
        }
        int value = parseAddition();
        if (position != expression.length()) {
            throw new IllegalArgumentException("Invalid verification expression: " + expression);
        }
        return value;
    }

    private int parseAddition() {
        int value = parseMultiplication();
        while (position < expression.length()) {
            char operator = expression.charAt(position++);
            int right = parseMultiplication();
            if (operator == '+') {
                value += right;
            } else if (operator == '-') {
                value -= right;
            } else {
                position--;
                return value;
            }
        }
        return value;
    }

    private int parseMultiplication() {
        int value = parseNumber();
        while (position < expression.length() && expression.charAt(position) == '*') {
            position++;
            value *= parseNumber();
        }
        return value;
    }

    private int parseNumber() {
        int start = position;
        while (position < expression.length() && Character.isDigit(expression.charAt(position))) {
            position++;
        }
        if (start == position) {
            throw new IllegalArgumentException("Expected number in verification expression: " + expression);
        }
        return Integer.parseInt(expression.substring(start, position));
    }
}
